<?php

/**
 * PluginacPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginacPage extends BaseacPage
{
	public function __toString()
	{
		return $this->internal_name;
	}
	
	public function preSave($event)
	{
		if (isset($this->keywords))
			$this->setKeywords(strtolower($this->getKeywords()));
	}
}