<?php

/**
 * PluginacMenuOldUrlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginacMenuOldUrlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginacMenuOldUrlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginacMenuOldUrl');
    }
}